### ISSUE TITLE
The database path cannot be modified

### ISSUE THREAD

**Issue by wingkingbobo** [anboralabs/spatia-room#23]
To specify the database file path, I override `Context.getDatabasePath()`.
But SpatiaBuilder used 'context.applicationContext'.
Can it use context directly?

```kotlin
class SpatiaBuilder<T : RoomDatabase?> (
    context: Context,
    klass: Class<T>,
    name: String
): SpatiaRoom.Builder<T> {

    private val roomBuilder = Room.databaseBuilder(
        context.applicationContext,
        klass,
        name
    ).createFromAsset(templateDb)
        .openHelperFactory(SpatiaHelperFactory())
}
```

**Comment by dalgarins** [comment]
This issue is not part of spatiaroom, change your implementation because that's is the reason why you can't change the database location.
