### ISSUE TITLE
Using ST_Intersect with GeomFromGeoJSON is very slow.

### ISSUE THREAD

**Issue by arshdoda** [anboralabs/spatia-room#33]
I am using this library for filtering point,line and polygon using the intersection of bounding box and geojson data.
`ST_INTERSECTS(GeomFromGeoJSON(g), GeomFromGeoJSON('$bbox')) LIMIT 100`. 
Its very slow for complex multipolygons. If i change the LIMIT to 5. it works fine

**Comment by dalgarins** [comment]
also there is some information useful to you: https://groups.google.com/g/spatialite-users/c/pzW8TArb4rQ
