### ISSUE TITLE
Add a createFromFile method

### ISSUE THREAD

**Issue by akelian** [anboralabs/spatia-room#40]
Hi! Can you please add a createFromFile method to databaseBuilder?
We are working in no internet enviroment for mobile devices so only way to synchronize data with server is load sqlite file into device directly via PC. Unfortunately createFromAsset method isn't suitable.

**Comment by dalgarins** [comment]
@akelian I'll be working on that.

**Comment by dalgarins** [comment]
@akelian new version 0.2.8, has the method you need.

**Comment by akelian** [comment]
@dalgarins Thank you! You helped me a lot
