### ISSUE TITLE
Is possible to load db from external files?

### ISSUE THREAD

**Issue by hitmacreed** [anboralabs/spatia-room#54]
Hi i understand that we have this method

```
Deprecated(message = "This API is experimental. It may be changed in the future without notice.", level = DeprecationLevel.WARNING)
fun createFromAsset(databaseFilePath: String): Builder<T>
```

But this only work for inernal app assets , wonder if its possible to access external files on android.

In the scenario that the DB are large(in my case 300MB) this will increase the app size as well

**Comment by dalgarins** [comment]
> @hitmacreed you also have this method: `    override fun createFromFile(databaseFile: File): SpatiaRoom.Builder<T>`

With the file reference you can use an external db.

**Comment by hitmacreed** [comment]
> @hitmacreed you also have this method: `fun createFromFile(databaseFile: File): SpatiaRoom.Builder<T>`
> 
> With the file reference you can use an external db.

Will give it a try thanks
